version: '3.5'

services:
  stats-analyzer:
    image: lvapeab/feb-stats:latest
    ports:
      - '80:80'
    networks:
      - feb-stats
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 5
        window: 120s

networks:
  feb-stats:
