version: '3'

services:
  stats-analyzer:
    build:
      context: .
      dockerfile: Dockerfile_python_server
    ports:
      - '50001:50001'
    networks:
      - feb-stats-network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 60s
        max_attempts: 5
        window: 300s

  node-app:
    build:
      context: .
      dockerfile: Dockerfile_web_server
    ports:
      - '80:80'
    environment:
      GRPC_PORT: '50001'
      WEB_PORT: '80'
    networks:
      - feb-stats-network
    depends_on:
      - stats-analyzer
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 5
        window: 120s

  jaeger-tracing:
    image: jaegertracing/all-in-one:1.18
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '14250:14250'
      - '9411:9411'
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: '9411'
    networks:
      - feb-stats-network

networks:
  feb-stats-network:
