version: '3.5'

services:
  stats-analyzer:
    image: lvapeab/feb-stats:0.2
    ports:
      - '50001:50001'
    networks:
      - feb-stats-network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 60s
        max_attempts: 5
        window: 300s

  node-app:
    image: lvapeab/feb-stats:0.2
    ports:
      - '80:80'
    environment:
      GRPC_PORT: '50001'
      WEB_PORT: '80'
    networks:
      - feb-stats-network
    depends_on:
      - stats-analyzer
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 5
        window: 120s

networks:
  feb-stats-network:
