version: '3.5'

services:
  stats-analyzer:
    image: lvapeab/feb-stats:0.1
    ports:
      - '50001:50001'
    networks:
      - feb-stats-network


  node-app:
    image: lvapeab/feb-stats_web:0.1
    ports:
      - '8080:8080'
    environment:
      GRPC_PORT: '50001'
      WEB_PORT: '8080'
    networks:
      - feb-stats-network
    depends_on:
      - stats-analyzer





networks:
  feb-stats-network:
