version: '3.5'

services:
  stats-analyzer:
    build:
      context: ./
      dockerfile: Dockerfile_python_server
    ports:
      - '50001:50001'
    networks:
      - feb-stats-network


  node-app:
    build:
      context: ./
      dockerfile: Dockerfile_web_server
    ports:
      - '80:80'
    environment:
      GRPC_PORT: '50001'
      WEB_PORT: '80'
    networks:
      - feb-stats-network
    depends_on:
      - stats-analyzer

networks:
  feb-stats-network:
