
version: '3'

services:
  stats-analyzer:
    image: lvapeab/feb-stats:latest
    command: bazel run //python/service:server
    ports:
      - '50001:50001'
    networks:
      - feb-stats
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 60s
        max_attempts: 5
        window: 300s

  node-app:
    image: lvapeab/feb-stats:latest
    command: bazel run //js/node:app
    ports:
      - '80:80'
    networks:
      - feb-stats
    depends_on:
      - stats-analyzer
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 5
        window: 120s

networks:
  feb-stats:
