version: '3.5'

services:
  stats-analyzer:
    image: lvapeab/feb-stats:latest
    build:
      context: .
    ports:
      - '80:80'
    networks:
      - feb-stats
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 5

networks:
  feb-stats:
