spanish_columns = {
    "oer": "OER",
    "der": "DER",
    "games": "PAR",
    "points_made": "PTOS FAV",
    "points_received": "PTOS CON",
    "total_possessions": "POS",
    "minutes": "MIN",
    "assists": "ASIS",
    "steals": "ROB",
    "turnovers": "PERD",
    "two_point_percentage": "T2 %",
    "two_point_made": "T2 Met",
    "two_point_attempted": "T2 Tot",
    "three_point_percentage": "T3 %",
    "three_point_made": "T3 Met",
    "three_point_attempted": "T3 int",
    "field_goal_percentage": "TC %",
    "field_goal_made": "TC Met",
    "field_goal_attempted": "TC Int",
    "free_throw_percentage": "TL %",
    "free_throw_made": "TL Met",
    "free_throw_attempted": "TL Int",
    "offensive_rebounds": "REB DEF",
    "defensive_rebounds": "REB OF",
    "total_rebounds": "REB TOT",
    "fouls_made": "FAL COM",
    "fouls_received": "FAL REC",
    "blocks_made": "TAP FAV",
    "blocks_received": "TAP CON",
    "dunks": "Mates",
    "ranking": "VAL",
    "point_balance": "+/-",
    "team": "EQUIPO",
    "mode": "MODO",
    "points_made_volume": "VOL PTOS FAV",
    "total_possessions_volume": "VOL POS",
    "two_point_made_volume": "VOL T2 Met",
    "two_point_attempted_volume": "VOL T2 Tot",
    "three_point_made_volume": "VOL T3 Met",
    "three_point_attempted_volume": "VOL T3 Tot",
    "field_goal_made_volume": "VOL TC Met",
    "field_goal_attempted_volume": "VOL TC Tot",
    "free_throw_made_volume": "VOL TL Met",
    "free_throw_attempted_volume": "VOL TL Tot",
    "offensive_rebounds_volume": "VOL REB DEF",
    "defensive_rebounds_volume": "VOL REB OF",
    "total_rebounds_volume": "VOL REB TOT",
    "oer_40_min": "40 Min OER",
}
