[tool.poetry]
name = "feb-stats"
version = "0.1.0"
description = "FEB stats parser."
authors = ["Álvaro Peris <lvapeab@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.0.3"
lxml = "^4.5.1"
requests = "^2.23.0"
xlsxwriter = "^1.2.8"
pysimplegui = "^4.19.0"
numpy = "^1.18.5"
"keyrings.alt" = "^3.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
