"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import typing

import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetFebStatsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BOXSCORES_FIELD_NUMBER: builtins.int
    COLOR_SHEET_FIELD_NUMBER: builtins.int
    color_sheet: builtins.bool
    @property
    def boxscores(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        boxscores: collections.abc.Iterable[builtins.bytes] | None = ...,
        color_sheet: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["boxscores", b"boxscores", "color_sheet", b"color_sheet"]) -> None: ...

global___GetFebStatsRequest = GetFebStatsRequest

@typing.final
class GetFebStatsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SHEET_FIELD_NUMBER: builtins.int
    TEAMS_FIELD_NUMBER: builtins.int
    sheet: builtins.bytes
    @property
    def teams(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        sheet: builtins.bytes = ...,
        teams: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["sheet", b"sheet", "teams", b"teams"]) -> None: ...

global___GetFebStatsResponse = GetFebStatsResponse
