# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: feb_stats.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 28, 1, "", "feb_stats.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0f\x66\x65\x62_stats.proto\x12\tfeb_stats"<\n\x12GetFebStatsRequest\x12\x11\n\tboxscores\x18\x01 \x03(\x0c\x12\x13\n\x0b\x63olor_sheet\x18\x02 \x01(\x08"3\n\x13GetFebStatsResponse\x12\r\n\x05sheet\x18\x01 \x01(\x0c\x12\r\n\x05teams\x18\x02 \x03(\t2_\n\x0f\x46\x65\x62StatsService\x12L\n\x0bGetFebStats\x12\x1d.feb_stats.GetFebStatsRequest\x1a\x1e.feb_stats.GetFebStatsResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "feb_stats_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_GETFEBSTATSREQUEST"]._serialized_start = 30
    _globals["_GETFEBSTATSREQUEST"]._serialized_end = 90
    _globals["_GETFEBSTATSRESPONSE"]._serialized_start = 92
    _globals["_GETFEBSTATSRESPONSE"]._serialized_end = 143
    _globals["_FEBSTATSSERVICE"]._serialized_start = 145
    _globals["_FEBSTATSSERVICE"]._serialized_end = 240
# @@protoc_insertion_point(module_scope)
