# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from . import feb_stats_pb2 as feb__stats__pb2

GRPC_GENERATED_VERSION = "1.68.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in feb_stats_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class FebStatsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFebStats = channel.unary_unary(
            "/feb_stats.FebStatsService/GetFebStats",
            request_serializer=feb__stats__pb2.GetFebStatsRequest.SerializeToString,
            response_deserializer=feb__stats__pb2.GetFebStatsResponse.FromString,
            _registered_method=True,
        )


class FebStatsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFebStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_FebStatsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetFebStats": grpc.unary_unary_rpc_method_handler(
            servicer.GetFebStats,
            request_deserializer=feb__stats__pb2.GetFebStatsRequest.FromString,
            response_serializer=feb__stats__pb2.GetFebStatsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("feb_stats.FebStatsService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("feb_stats.FebStatsService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class FebStatsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFebStats(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/feb_stats.FebStatsService/GetFebStats",
            feb__stats__pb2.GetFebStatsRequest.SerializeToString,
            feb__stats__pb2.GetFebStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
