name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      # Stable version doesn't currently work (https://github.com/psf/black/issues/1520)
      - uses: psf/black@fcf97961061982656a1384ecc1628e217a52a88c