name: CI

on: [push, pull_request]

jobs:
  test-linux:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
          lfs: true

    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: "pipenv"

    - name: Setup PIpenv
      uses: abatilo/actions-poetry@v4

    - name: Install Dependencies
      run: poetry install
    - uses: actions/cache@v3
      name: Define a cache for the virtual environment based on the dependencies lock file
      with:
        path: ./.venv
        key: venv-${{ hashFiles('poetry.lock') }}

    - name: Run Lint
      run: poetry run lint

    - name: Run tests with coverage
      run: | 
        poetry run pytest tests \
          --cov=./ \
          --cov-report=term-missing \
          --cov-fail-under=88
