name: CI

on: [push, pull_request]

jobs:
  test-linux:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
          lfs: true

    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: "pipenv"

    - name: Setup PIpenv
      uses: tiagovrtr/actions-pipenv@v1
      with:
        pipenv-version: v2024.4.0

    - name: Install Dependencies
      run: pipenv install --dev

    - name: Run Lint
      run: pipenv run lint

    - name: Run tests with coverage
      run: | 
        pipenv run pytest tests \
          --cov=./ \
          --cov-report=term-missing \
          --cov-fail-under=88
