name: CI

on: [push, pull_request]

jobs:

  lint:
    name: Lint
    runs-on: [ubuntu-latest]
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Lint
      run: ./travis/kyaml-pre-commit.sh
      env:
        KUSTOMIZE_DOCKER_E2E: false # don't need to do e2e tests for linting




  test-linux:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
          lfs: true

    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Update pip
      run: |
        python -m pip install --upgrade pip
        pip install wheel

    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.5.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    - name: Test
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test  --test_output=all --test_verbose_timeout_warnings //...

    - name: Build
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" build //...