on: push
name: Bazel tests
jobs:
  checks:
    name: run
    runs-on: ubuntu-18.04
    steps:
    - name: Set up
      uses: actions/checkout@master

    - name: run tests
      uses: ngalaiko/bazel-action/1.2.1@master
      with:
        python-version: "3.7"
        args: test --sandbox_debug //...