name: CI

on: [push, pull_request]

jobs:
  test-linux:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
          lfs: true

    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Setup Poetry
      uses: abatilo/actions-poetry@v2.1.6
      with:
        poetry-version: 1.1.15

    - name: Run Lint
      run: |
        poetry run black .
        poetry run isort .
        poetry run mypy .
        poetry run flake8 .

    - name: Run tests
      run: poetry run pytest tests
