on: push
name: Bazel tests
jobs:
  checks:
    name: run
    runs-on: python3.7
    steps:
    - uses: actions/checkout@master

    - name: run tests
      uses: ngalaiko/bazel-action/1.2.1@master
      with:
        args: test //...