name: CI

on: [push, pull_request]

jobs:
  test-linux:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
          lfs: true

    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.8.12"

    - name: Set up Python
      run: uv python install

    - name: Install Dependencies
      run: uv sync --locked --extra=dev

    - uses: actions/cache@v3
      name: Define a cache for the virtual environment based on the dependencies lock file
      with:
        path: ./.venv
        key: venv-${{ hashFiles('uv.lock') }}

    - name: Run Lint
      run: uv run lint

    - name: Run tests with coverage
      run: | 
        uv run pytest tests  --ds=feb_stats.settings.testing \
          --cov=./ \
          --cov-report=term-missing \
          --cov-fail-under=88